NATS:
  host: 192.168.9.208
  port: 4222
  cache_ttl: 3600
  subscriptions:
    alert: object.alerttype.test
    case: object.casetype.test
  command: object.commandstype.test
DATABASESTORAGE:
  host: datahook.cloud.gcm
  port: 9200
  user: writer
  namedb: ""
  storage_name_db:
    alert: test.module_placeholderdb_alert
    case: test.module_placeholderdb_case
DATABASEWRITELOG:
  host: datahook.cloud.gcm
  port: 9200
  user: log_writer
  namedb: ""
  storage_name_db: placeholder_doc-base-db
