NATS:
  host: nats.cloud.gcm
  port: 4222
  cache_ttl: 3600
  subscriptions:
    alert: object.alerttype
    case: object.casetype
  command: object.commandstype
  requests:
    get_geoip_info: object.geoip-request
    get_sensor_info: object.sensor-info-request
DATABASESTORAGE:
  host: datahook.cloud.gcm
  port: 9200
  user: writer
  namedb: ""
  storage_name_db:
    alert: module_placeholderdb_alert
    case: module_placeholderdb_case
DATABASEWRITELOG:
  host: datahook.cloud.gcm
  port: 9200
  user: log_writer
  namedb: ""
  storage_name_db: placeholder_doc-base-db
