NATS:
  host: 192.168.9.208
  port: 4222
  cache_ttl: 3600
  subscriptions:
    alert: object.alerttype.test
    case: object.casetype.test
  command: object.commandstype.test
  requests:
    get_geoip_info: object.geoip-request.test
    get_sensor_info: object.sensor-info-request.test
DATABASESTORAGE:
  host: 192.168.9.208
  port: 9200
  user: placeholder-docbase-db
  namedb: ""
  storage_name_db:
    alert: testtt.module_placeholderdb_alert
    case: testtt.module_placeholderdb_case
DATABASEWRITELOG:
  host: 192.168.9.208
  port: 9200
  user: placeholder-docbase-db
  namedb: ""
  storage_name_db: placeholder_doc-base-db
