NATS:
  host: 192.168.9.208
  port: 4222
  cache_ttl: 3600
  subscriptions:
    listener_case: object.casetype.test
    listener_alert: object.alerttype.test
    sender_command: object.commandstype.test
DATABASESTORAGE:
  - host: datahook.cloud.gcm
    port: 9200
    namedb: ""
    storage_name_db: test_module_placeholder_alert
    user: writer
  - host: datahook.cloud.gcm
    port: 9200
    namedb: ""
    storage_name_db: test_module_placeholder_case
    user: writer
DATABASEWRITELOG:
  host: datahook.cloud.gcm
  port: 9200
  namedb: ""
  storage_name_db: placeholder_misp
  user: log_writer
